name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Add target
        run: rustup target add ${{ matrix.target }}

      - name: Build the project
        run: cargo build --release --target ${{ matrix.target }}

      - name: Package the binary
        run: |
          mkdir -p release
          BINARY_NAME=rcon-echo
          cp target/${{ matrix.target }}/release/$BINARY_NAME release/$BINARY_NAME-${{ matrix.target }}

      - name: Upload binaries as release assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/${{ matrix.target }}/release/$BINARY_NAME
          asset_name: $BINARY_NAME-${{ matrix.target }}
          asset_content_type: application/octet-stream
