name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-msvc
          - x86_64-apple-darwin
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Add target
        run: rustup target add ${{ matrix.target }}

      - name: Build the project
        run: cargo build --release --target ${{ matrix.target }}

      - name: Package the binary
        run: |
          mkdir -p release
          BINARY_NAME=$(basename $(pwd))
          if [[ "${{ matrix.target }}" == *"windows"* ]]; then
            cp target/${{ matrix.target }}/release/$BINARY_NAME.exe release/$BINARY_NAME-${{ matrix.target }}.exe
          else
            cp target/${{ matrix.target }}/release/$BINARY_NAME release/$BINARY_NAME-${{ matrix.target }}
          fi

      - name: Upload binaries as release assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release/$BINARY_NAME-${{ matrix.target }}$(if [[ "${{ matrix.target }}" == *"windows"* ]]; then echo .exe; fi)
          asset_name: $BINARY_NAME-${{ matrix.target }}$(if [[ "${{ matrix.target }}" == *"windows"* ]]; then echo .exe; fi)
          asset_content_type: application/octet-stream
